Shmap\shmapBundle\Entity\Shop:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: '70'
        description:
            type: text
        visits:
            type: integer
    lifecycleCallbacks: {  }
